mod dest;
mod download;
mod event;
mod gate;
mod ports;
mod proxy;
mod public_url;
mod qr;
mod sanitize;
mod share;
mod transfer;
mod upload;
mod util;

#[cfg(test)]
#[path = "../test/regressions.rs"]
mod regressions;

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand, ValueEnum};
use cloudflare_quick_tunnel::{QuickTunnelHandle, QuickTunnelManager};
use hyper_util::{rt::TokioIo, service::TowerToHyperService};
use tokio::net::TcpListener;
use tokio::sync::watch;
use tokio::task::JoinSet;
use tokio_util::sync::CancellationToken;
use uuid::Uuid;

use crate::dest::DestDir;
use crate::event::Event;
use crate::share::ShareFile;
use crate::upload::SessionUsed;

const MIN_FILE_BYTES: u64 = 1024 * 1024;
const MAX_FILE_BYTES: u64 = 2048 * 1024 * 1024;
const MIN_IDLE_SECS: u64 = 60;
const MAX_IDLE_SECS: u64 = 120 * 60;
const MAX_FILES: u32 = 32;
const SHUTDOWN_GRACE: Duration = Duration::from_secs(1);

#[derive(Parser, Debug)]
#[command(
    name = "quickbridge",
    version,
    about = "Phone-to-desktop bridge helper for Omarchy"
)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Start an upload, download, or proxy session.
    Serve(ServeArgs),
    /// List local HTTP ports that can be shared.
    Ports,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
enum Mode {
    Upload,
    Download,
    Proxy,
}

#[derive(clap::Args, Debug)]
struct ServeArgs {
    #[arg(long, value_enum)]
    mode: Mode,

    /// Directory that receives uploaded files (upload mode).
    #[arg(long)]
    dest: Option<PathBuf>,

    /// Maximum size of a single file, in bytes.
    #[arg(long, default_value_t = 100 * 1024 * 1024)]
    max_bytes: u64,

    /// Stop the tunnel after this many idle seconds.
    #[arg(long, default_value_t = 15 * 60)]
    idle_secs: u64,

    /// Serve on localhost only; skip the Cloudflare tunnel.
    #[arg(long)]
    no_tunnel: bool,

    /// Stop after the first successful upload or download.
    #[arg(long)]
    stop_after: bool,

    /// File to share (download mode).
    #[arg(long)]
    file: Option<PathBuf>,

    /// Share the current clipboard (download mode).
    #[arg(long)]
    clipboard: bool,

    /// Delete --file after opening it (clipboard snapshots).
    #[arg(long)]
    ephemeral: bool,

    /// Local HTTP port to share (proxy mode).
    #[arg(long)]
    port: Option<u16>,

    /// Require a 6-digit PIN generated by the helper (not placed in the URL).
    #[arg(long)]
    password: bool,
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| {
                tracing_subscriber::EnvFilter::new(
                    "warn,quickbridge=info,cloudflare_quick_tunnel=warn",
                )
            }),
        )
        .with_writer(std::io::stderr)
        .init();

    if let Err(err) = run().await {
        event::error(format!("{err:#}"));
        std::process::exit(1);
    }
}

async fn run() -> Result<()> {
    match Cli::parse().cmd {
        Cmd::Serve(args) => serve(args).await,
        Cmd::Ports => ports::run().await,
    }
}

enum Prepared {
    Upload { dest: DestDir },
    Download { share: ShareFile },
    Proxy { target: SocketAddr },
}

async fn serve(args: ServeArgs) -> Result<()> {
    let max_bytes = args.max_bytes.clamp(MIN_FILE_BYTES, MAX_FILE_BYTES);
    let idle_secs = args.idle_secs.clamp(MIN_IDLE_SECS, MAX_IDLE_SECS);
    let last_activity = Arc::new(Mutex::new(Instant::now()));
    let started = Instant::now();
    let (stop_tx, stop_rx) = watch::channel(false);
    let no_tunnel = args.no_tunnel;
    let stop_after = args.stop_after;

    event::progress("starting", "Starting Quick Bridge…", 0.08);

    let prepared = match args.mode {
        Mode::Upload => {
            let dest = DestDir::prepare(args.dest)?;
            Prepared::Upload { dest }
        }
        Mode::Download => {
            if args.clipboard && args.file.is_some() {
                bail!("use --file or --clipboard, not both");
            }
            let share = if args.clipboard {
                event::progress("starting", "Reading the clipboard…", 0.18);
                share::capture_clipboard(max_bytes)?
            } else if let Some(path) = args.file {
                share::open_file(path, max_bytes, args.ephemeral)?
            } else {
                bail!("download mode needs --file or --clipboard");
            };
            Prepared::Download { share }
        }
        Mode::Proxy => {
            let target = args.port.context("proxy mode needs --port")?;
            if target == 0 {
                bail!("invalid port");
            }
            event::progress("starting", format!("Checking localhost:{target}…"), 0.16);
            let target = ports::confirm_local_http(target).await?;
            Prepared::Proxy { target }
        }
    };

    let listener = TcpListener::bind("127.0.0.1:0")
        .await
        .context("could not bind local server")?;
    let port = listener.local_addr()?.port();
    if let Prepared::Proxy { target } = &prepared {
        if target.port() == port {
            bail!("refusing to proxy the helper's own port");
        }
    }

    let (origin, location, tunnel) = if no_tunnel {
        event::progress("starting", "Listening on localhost…", 0.55);
        (
            public_url::local_origin(&format!("http://127.0.0.1:{port}"), port)?,
            "local".to_string(),
            None,
        )
    } else {
        let handle = open_tunnel(port).await?;
        let origin = public_url::tunnel_origin(&handle.url)?;
        let location = public_url::sanitize_location(&handle.location);
        (origin, location, Some(handle))
    };

    let idle = Duration::from_secs(idle_secs);
    let wall = idle.saturating_mul(2);
    let token = Uuid::new_v4().simple().to_string();
    let gate = if args.password || matches!(args.mode, Mode::Proxy) {
        crate::gate::Gate::pin(!no_tunnel)
    } else {
        crate::gate::Gate::off()
    };
    let password = gate.pin_display();

    let app = match prepared {
        Prepared::Upload { dest } => {
            let url = public_url::session_url(&origin, &token)?;
            let qr = qr_ready(&url)?;
            event::emit(&Event::Ready {
                url,
                dest: dest.path.to_string_lossy().into_owned(),
                qr,
                location,
                mode: "upload".into(),
                name: None,
                port: None,
                password: password.clone(),
            });
            let max_session_bytes = max_bytes.saturating_mul(8).min(8 * 1024 * 1024 * 1024);
            upload::router(upload::AppState {
                token,
                dest,
                max_bytes,
                max_session_bytes,
                max_files: MAX_FILES,
                last_activity: last_activity.clone(),
                used: Arc::new(Mutex::new(SessionUsed { bytes: 0, files: 0 })),
                stop_after,
                shutdown: stop_tx,
                gate,
            })
        }
        Prepared::Download { share } => {
            let url = public_url::session_url(&origin, &token)?;
            let qr = qr_ready(&url)?;
            let dest = if share.path.is_absolute() {
                share.path.to_string_lossy().into_owned()
            } else {
                share.name.clone()
            };
            event::emit(&Event::Ready {
                url,
                dest,
                qr,
                location,
                mode: "download".into(),
                name: Some(share.name.clone()),
                port: None,
                password: password.clone(),
            });
            download::router(download::AppState {
                token,
                share,
                last_activity: last_activity.clone(),
                stop_after,
                shutdown: stop_tx,
                gate,
            })
        }
        Prepared::Proxy { target } => {
            let url = public_url::proxy_url(&origin)?;
            let qr = qr_ready(&url)?;
            event::emit(&Event::Ready {
                url,
                dest: format!("http://{target}"),
                qr,
                location,
                mode: "proxy".into(),
                name: None,
                port: Some(target.port()),
                password,
            });
            proxy::router(proxy::AppState {
                target,
                client: proxy::client(),
                last_activity: last_activity.clone(),
                tunneled: !no_tunnel,
                gate,
                limit: std::sync::Arc::new(tokio::sync::Semaphore::new(
                    proxy::MAX_PROXY_CONCURRENT,
                )),
            })
        }
    };

    let serve_result =
        serve_until_ready(listener, app, last_activity, started, idle, wall, stop_rx).await;

    if let Some(handle) = tunnel {
        match tokio::time::timeout(SHUTDOWN_GRACE, handle.shutdown()).await {
            Ok(Ok(())) => {}
            Ok(Err(err)) => tracing::warn!("tunnel shutdown: {err}"),
            Err(_) => tracing::warn!("tunnel shutdown timed out; exiting helper"),
        }
    }
    serve_result.context("bridge server stopped")?;
    Ok(())
}

fn qr_ready(url: &str) -> Result<Vec<String>> {
    event::progress("starting", "Preparing the QR code…", 0.96);
    qr::matrix_for(url)
}

async fn serve_until_ready(
    listener: TcpListener,
    make: axum::Router,
    last_activity: Arc<Mutex<Instant>>,
    started: Instant,
    idle: Duration,
    wall: Duration,
    mut stop_rx: watch::Receiver<bool>,
) -> std::io::Result<()> {
    let shutdown = async move {
        tokio::select! {
            _ = shutdown_signal() => {}
            _ = idle_watch(last_activity, idle) => {}
            _ = wall_watch(started, wall) => {}
            _ = async { let _ = stop_rx.wait_for(|v| *v).await; } => {}
        }
    };
    tokio::pin!(shutdown);
    let draining = CancellationToken::new();
    let mut connections = JoinSet::new();
    loop {
        tokio::select! {
            biased;
            _ = &mut shutdown => break,
            Some(_) = connections.join_next(), if !connections.is_empty() => {}
            accepted = listener.accept() => {
                let (stream, _) = accepted?;
                let service = TowerToHyperService::new(make.clone());
                let (deadline_tx, deadline_rx) = watch::channel(None);
                let deadline = transfer::ConnectionDeadline(deadline_tx);
                let service = hyper::service::service_fn(move |mut request: hyper::Request<hyper::body::Incoming>| {
                    request.extensions_mut().insert(deadline.clone());
                    hyper::service::Service::call(&service, request)
                });
                let draining = draining.clone();
                connections.spawn(async move {
                    let builder = hyper::server::conn::http1::Builder::new();
                    let connection = builder.serve_connection(TokioIo::new(stream), service);
                    tokio::pin!(connection);
                    tokio::select! {
                        // Closing the socket also cancels a stalled upload or a
                        // response whose receiver has stopped reading.
                        _ = transfer::wait_deadline(deadline_rx) => {}
                        _ = draining.cancelled() => {
                            connection.as_mut().graceful_shutdown();
                            let _ = connection.await;
                        }
                        _ = &mut connection => {}
                    }
                });
            }
        }
    }
    drop(listener);
    draining.cancel();
    if tokio::time::timeout(SHUTDOWN_GRACE, async {
        while connections.join_next().await.is_some() {}
    })
    .await
    .is_err()
    {
        // Unlike dropping axum::serve, aborting these owned tasks closes every
        // active socket and drops pending request bodies and upload guards.
        connections.abort_all();
        while connections.join_next().await.is_some() {}
    }
    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = tokio::signal::ctrl_c();
    #[cfg(unix)]
    {
        let mut term = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("install SIGTERM handler");
        tokio::select! {
            _ = ctrl_c => {}
            _ = term.recv() => {}
        }
    }
    #[cfg(not(unix))]
    {
        let _ = ctrl_c.await;
    }
}

async fn idle_watch(last: Arc<Mutex<Instant>>, idle: Duration) {
    loop {
        let elapsed = Instant::now().saturating_duration_since(*last.lock().unwrap());
        if elapsed >= idle {
            event::status(
                "idle-timeout",
                Some("Stopped after idle timeout".to_string()),
            );
            break;
        }
        tokio::time::sleep(idle - elapsed).await;
    }
}

async fn wall_watch(started: Instant, wall: Duration) {
    let elapsed = Instant::now().saturating_duration_since(started);
    tokio::time::sleep(wall.saturating_sub(elapsed)).await;
    event::status(
        "session-timeout",
        Some("Stopped after session time limit".to_string()),
    );
}

async fn open_tunnel(port: u16) -> Result<QuickTunnelHandle> {
    event::progress("connecting", "Requesting a Cloudflare tunnel…", 0.22);

    let (stop_tx, mut stop_rx) = tokio::sync::oneshot::channel::<()>();
    let ticker = tokio::spawn(async move {
        let steps = [
            (
                Duration::from_millis(700),
                0.34,
                "Finding a Cloudflare edge…",
            ),
            (
                Duration::from_millis(900),
                0.46,
                "Handshaking with the edge…",
            ),
            (
                Duration::from_millis(1100),
                0.56,
                "Registering this computer…",
            ),
        ];
        for (delay, value, message) in steps {
            tokio::select! {
                _ = &mut stop_rx => return,
                _ = tokio::time::sleep(delay) => {}
            }
            event::progress("connecting", message, value);
        }
        let mut value: f64 = 0.58;
        loop {
            tokio::select! {
                _ = &mut stop_rx => return,
                _ = tokio::time::sleep(Duration::from_millis(750)) => {}
            }
            value = (value + 0.012).min(0.68);
            event::progress("connecting", "Waiting on Cloudflare…", value);
        }
    });

    let result = QuickTunnelManager::new(port)
        .with_user_agent(format!("quickbridge/{}", env!("CARGO_PKG_VERSION")))
        .with_ha_connections(1)
        .start()
        .await
        .context("could not open a Cloudflare quick tunnel");
    let _ = stop_tx.send(());
    let _ = ticker.await;
    result
}
